using Test
using DynamicPolynomials: @polyvar, terms, powers, monomial, coefficient, coefficient_type

include("../faster_f5b.jl")

# TODO - move to utilities file
function quick_lp(idx, sig_exps, poly_dynamic, vars)
    p = from_dynamic(poly_dynamic, vars)
    sig = pack_exponents(sig_exps)
    return LabelledPolynomial(idx, sig, p)
end

@testset "F5B Rewritten Criterion Unit Tests" begin
    @polyvar x1 x2 x3
    vars = [x1, x2, x3]
    num_vars = 3
    C = Rational{Int64}

    # Define some base polynomials for B
    # g1: index 1, signature 1, poly x1 + x2
    g1 = quick_lp(1, [0, 0, 0], C(1)x1 + C(1)x2, vars)
    # g2: index 2, signature 1, poly x2 + x3
    g2 = quick_lp(2, [0, 0, 0], C(1)x2 + C(1)x3, vars)
    
    B = [g1, g2]

    @testset "rewritable" begin
        # rewritable(F, F_gen, G, G_gen) returns true if:
        # F_gen < G_gen AND G.index == F.index AND G.sig divides F.sig
        
        # Let F be a polynomial currently being checked, generated by B[idx=10]
        # Let G be an existing basis element in B[idx=5]
        # Both share original generator index 2.
        F_gen_idx = 10
        G_gen_idx = 5
        
        F = quick_lp(2, [2, 0, 0], C(1)x1, vars) # Sig: (2, x1^2)
        G = quick_lp(2, [1, 0, 0], C(1)x1, vars) # Sig: (2, x1)
        
        # Since 10 > 5, we check if F is rewritable by G
        # Note: Your function signature is rewritable(F, F_gen, G, G_gen)
        # So we pass F_gen_idx (10) as F_gen and i (5) as G_gen
        @test rewritable(F, F_gen_idx, G, G_gen_idx, num_vars) == false # Because F_gen < G_gen is false
        
        # Correct direction: Is a NEWER polynomial (G_gen=10) rewritable by an OLDER one (F_gen=5)?
        # If the function is called as rewritable(uF, F_idx, LP, i...) 
        # F_gen is the index of the current pair in the loop, i is the basis index.
        @test rewritable(F, 5, G, 10, num_vars) == true
    end

    @testset "rewritten_criterion" begin
        # Checks if either uF or vG can be rewritten by anything in B
        
        # Setup B with a potential rewriter at index 1
        # G has index 2, sig x1
        rewriter = quick_lp(2, [1, 0, 0], C(1)x1, vars)
        B_rewriting = [rewriter]
        
        # uF has index 2, sig x1^2. We are currently processing pair (F_idx=5, G_idx=6)
        uF = quick_lp(2, [2, 0, 0], C(1)x1, vars)
        vG = quick_lp(3, [0, 0, 0], C(1)x1, vars)
        
        # Is uF (gen 5) rewritable by B[1] (gen 1)? 
        # rewritable(uF, 5, B[1], 1) -> 5 < 1 is false. 
        # Wait—In your loop: rewritten_criterion(uF, vG, B, F_idx, G_idx...)
        # It calls rewritable(uF, F_gen, LP, i).
        # To return true, F_gen must be < i.
        
        uF_low = quick_lp(2, [2, 0, 0], C(1)x1, vars)
        @test rewritten_criterion(uF_low, vG, B_rewriting, 0, 6, num_vars) == true
    end
end

@testset "SyzygyPool Optimized Criterion" begin
    @polyvar x1 x2 x3
    vars = [x1, x2, x3]
    num_vars = 3
    C = Rational{Int64}

    # 1. Setup a Basis B and a corresponding SyzygyPool
    # g1: index 1, LM = x1
    g1 = quick_lp(1, [0, 0, 0], C(1)x1 + C(1)x2, vars)
    # g2: index 5, LM = x2 (intentional gap in indices)
    g2 = quick_lp(5, [0, 0, 0], C(1)x2 + C(1)x3, vars)
    
    B = [g1, g2]
    
    # Sync SyzygyPool with Basis B
    # Pool stores (LM, index)
    pool = SyzygyPool(
        [leading_monomial(g1), leading_monomial(g2)], 
        [UInt16(1), UInt16(5)]
    )

    @testset "Single Signature Check" begin
        # F has signature x1^2 and original generator index 0.
        # Should be divisible by g1 (LM=x1, index=1) because 0 < 1.
        sig_f = pack_exponents([2, 0, 0])
        idx_f = UInt16(0)
        
        @test syzygy_criterion(pool, idx_f, sig_f, num_vars) == true

        # Change index to 2. Now 2 > 1 (g1) and 2 < 5 (g2).
        # But sig_f (x1^2) is NOT divisible by g2.LM (x2).
        # So it should be false.
        idx_f_high = UInt16(2)
        @test syzygy_criterion(pool, idx_f_high, sig_f, num_vars) == false
    end

    @testset "Double Signature Check (S-Pairs)" begin
        # uF: sig x1, index 0 (Hit against g1)
        # vG: sig x3, index 10 (Safe)
        uF_sig = pack_exponents([1, 0, 0])
        uF_idx = UInt16(0)
        vG_sig = pack_exponents([0, 0, 1])
        vG_idx = UInt16(10)

        @test syzygy_criterion(pool, uF_idx, uF_sig, vG_idx, vG_sig, num_vars) == true

        # Both safe
        @test syzygy_criterion(pool, UInt16(10), uF_sig, UInt16(10), vG_sig, num_vars) == false
    end

	@testset "Edge Case: Boundary Indices" begin
    	# Create a signature that ONLY divides g1
    	# g1.LM is x1. Let's use sig = x1 (no x2, so it won't divide g2.LM)
    	sig_only_g1 = pack_exponents([1, 0, 0]) 
    
    	# If idx is 1, and pool index is 1: 1 < 1 is false.
    	@test syzygy_criterion(pool, UInt16(1), sig_only_g1, num_vars) == false 
    
    	# If idx is 0, and pool index is 1: 0 < 1 is true.
    	@test syzygy_criterion(pool, UInt16(0), sig_only_g1, num_vars) == true
	end
end
