using Test
using DynamicPolynomials: @polyvar, terms, powers, monomial, coefficient, coefficient_type

include("../faster_f5b.jl")

# TODO - move to utilities file
function quick_lp(idx, sig_exps, poly_dynamic, vars)
    p = from_dynamic(poly_dynamic, vars)
    sig = pack_exponents(sig_exps)
    return LabelledPolynomial(idx, sig, p)
end

@testset "F5B Criterion Unit Tests" begin
    @polyvar x1 x2 x3
    vars = [x1, x2, x3]
    num_vars = 3
    C = Rational{Int64}

    # Define some base polynomials for B
    # g1: index 1, signature 1, poly x1 + x2
    g1 = quick_lp(1, [0, 0, 0], C(1)x1 + C(1)x2, vars)
    # g2: index 2, signature 1, poly x2 + x3
    g2 = quick_lp(2, [0, 0, 0], C(1)x2 + C(1)x3, vars)
    
    B = [g1, g2]

    @testset "divisible (Syzygy logic)" begin
        # divisible(F, G) returns true if:
        # F.index < G.index AND G.LM divides F.signature
        
        # Case 1: LM(g1) is x1. Let's make F have signature x1^2 and index 0.
        # Since 0 < 1 and x1 | x1^2, this should be true.
        f1 = quick_lp(0, [2, 0, 0], C(1)x3, vars)
        @test divisible(f1, g1, num_vars) == true

        # Case 2: Monomial divides, but Index is NOT lower
        # If F.index is 1 and G.index is 1, it should be false.
        f2 = quick_lp(1, [2, 0, 0], C(1)x3, vars)
        @test divisible(f2, g1, num_vars) == false

        # Case 3: Index is lower, but Monomial does NOT divide
        # LM(g1) is x1, F.sig is x2
        f3 = quick_lp(0, [0, 1, 0], C(1)x3, vars)
        @test divisible(f3, g1, num_vars) == false
    end

    @testset "syzygy_criterion" begin
        # Triggers if uF OR vG is 'divisible' by any element in B
        
        # Create a pair where uF's signature is divisible by LM(g1)
        # uF.sig = x1, index = 0. g1.LM = x1, index = 1.
        uF = quick_lp(0, [1, 0, 0], C(1)x1, vars)
        vG = quick_lp(5, [0, 0, 0], C(1)x1, vars) # Random non-violating vG
        
        @test syzygy_criterion(uF, vG, B, num_vars) == true
        
        # Create a pair that is safe
        uF_safe = quick_lp(5, [1, 0, 0], C(1)x1, vars) # index 5 > g1.index 1
        vG_safe = quick_lp(5, [0, 1, 0], C(1)x1, vars)
        @test syzygy_criterion(uF_safe, vG_safe, B, num_vars) == false
    end

    @testset "rewritable" begin
        # rewritable(F, F_gen, G, G_gen) returns true if:
        # F_gen < G_gen AND G.index == F.index AND G.sig divides F.sig
        
        # Let F be a polynomial currently being checked, generated by B[idx=10]
        # Let G be an existing basis element in B[idx=5]
        # Both share original generator index 2.
        F_gen_idx = 10
        G_gen_idx = 5
        
        F = quick_lp(2, [2, 0, 0], C(1)x1, vars) # Sig: (2, x1^2)
        G = quick_lp(2, [1, 0, 0], C(1)x1, vars) # Sig: (2, x1)
        
        # Since 10 > 5, we check if F is rewritable by G
        # Note: Your function signature is rewritable(F, F_gen, G, G_gen)
        # So we pass F_gen_idx (10) as F_gen and i (5) as G_gen
        @test rewritable(F, F_gen_idx, G, G_gen_idx, num_vars) == false # Because F_gen < G_gen is false
        
        # Correct direction: Is a NEWER polynomial (G_gen=10) rewritable by an OLDER one (F_gen=5)?
        # If the function is called as rewritable(uF, F_idx, LP, i...) 
        # F_gen is the index of the current pair in the loop, i is the basis index.
        @test rewritable(F, 5, G, 10, num_vars) == true
    end

    @testset "rewritten_criterion" begin
        # Checks if either uF or vG can be rewritten by anything in B
        
        # Setup B with a potential rewriter at index 1
        # G has index 2, sig x1
        rewriter = quick_lp(2, [1, 0, 0], C(1)x1, vars)
        B_rewriting = [rewriter]
        
        # uF has index 2, sig x1^2. We are currently processing pair (F_idx=5, G_idx=6)
        uF = quick_lp(2, [2, 0, 0], C(1)x1, vars)
        vG = quick_lp(3, [0, 0, 0], C(1)x1, vars)
        
        # Is uF (gen 5) rewritable by B[1] (gen 1)? 
        # rewritable(uF, 5, B[1], 1) -> 5 < 1 is false. 
        # Wait—In your loop: rewritten_criterion(uF, vG, B, F_idx, G_idx...)
        # It calls rewritable(uF, F_gen, LP, i).
        # To return true, F_gen must be < i.
        
        uF_low = quick_lp(2, [2, 0, 0], C(1)x1, vars)
        @test rewritten_criterion(uF_low, vG, B_rewriting, 0, 6, num_vars) == true
    end
end
